### ISSUE TITLE
Notice: Undefined index: label_translation_domain

### ISSUE THREAD

**Issue by BoShurik** [Prezent/prezent-grid-bundle#12]
Hello!

Trying this bundle but facing this problem:
```php
class OrderGridType extends GridType
{
    public function buildGrid(GridBuilder $builder, array $options = [])
    {
        $builder
            ->addColumn('id', StringType::class)
        ;
    }
}
```

throws `Notice: Undefined index: label_translation_domain`

Adding
```php
public function configureOptions(OptionsResolver $resolver)
{
    $resolver->setDefaults([
        'label_translation_domain' => null,
    ]);
}
```
throws `Notice: Undefined index: attr`

If I add default `attr` option

```php
public function configureOptions(OptionsResolver $resolver)
{
    $resolver->setDefaults([
        'label_translation_domain' => null,
        'attr' => null,
    ]);
}
```

I've got  `Notice: Undefined index: label_translation_domain` again

**Comment by sandermarechal** [comment]
Do the notices give any file/line information? That would be helpful. Also, what is your Symfony and PHP version?

Can you perhaps execute the test suite that comes along with this bundle and post the results? To run the test suite, clone this repository, then `cd` to your checkout and run `composer install` followed by `./phpunit`.

**Comment by BoShurik** [comment]
Hello! 
Looks like I have a typo when I add bundle at first time. Now I try to reproduce the issue but all works fine.
Sorry for inconvenience
