### ISSUE TITLE
sort_field_parameter and sort_order_parameter are never respected when rendering

### ISSUE THREAD

**Issue by deckchairlabs** [Prezent/prezent-grid-bundle#2]
When defining the sort_field_parameter or sort_order_parameter on a column, the defaults are never overridden in the rendered output of the grid. Awesome library and bundle by the way!

``` php
$builder->addColumn('status', 'string', [
  'label' => 'Status',
  'sortable' => true,
  'sort_field_parameter' => 'sorting'
]);
```

![screen shot 2015-12-09 at 3 53 49 pm](https://cloud.githubusercontent.com/assets/7539725/11677375/19237acc-9e8d-11e5-9b9c-a0bebad8e973.png)

**Comment by rjbijl** [comment]
Fixed it in master
