### ISSUE TITLE
Set data-sort-dir value to `asc` or `desc`, not `1` or `0`

### ISSUE THREAD

**Issue by seydu** [Prezent/prezent-grid-bundle#7]
View variable`sort_active` is used to render `data-sort-dir` attribute for sortable fields. Do not convert it to `boolean` so that we will have the expected behavior (the CSS targets `asc` and `desc`).

Or keep this extension as is but render `sort_order` for `data-sort-dir` value.

**Comment by sandermarechal** [comment]
Closed by merging of #8
